# Generated by Django 4.0.3 on 2022-08-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_song_dislikes_remove_song_likes_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
