# Generated by Django 4.0.3 on 2022-08-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_song_dislikes_alter_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='dislikes',
        ),
    ]
